name: Build and Push Docker Image to ghcr.io

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -f Dockerfile.azopenai -t ghcr.io/${{ github.repository_owner }}/private-gpt:latest .

      # Step 4: Push the Docker image
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/private-gpt:latest
